language: node_js
node_js:
- stable
cache:
  yarn: true

before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn

before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test
  - yarn test:integration
after_script: greenkeeper-lockfile-upload
