// flow-typed signature: 899b2b7694a31136bd4e8a1a8202b72c
// flow-typed version: <<STUB>>/acorn_v~5.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'acorn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'acorn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'acorn/dist/acorn_loose.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn_loose' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn' {
  declare module.exports: any;
}

declare module 'acorn/dist/walk.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'acorn/dist/acorn_loose.es.js' {
  declare module.exports: $Exports<'acorn/dist/acorn_loose.es'>;
}
declare module 'acorn/dist/acorn_loose.js' {
  declare module.exports: $Exports<'acorn/dist/acorn_loose'>;
}
declare module 'acorn/dist/acorn.es.js' {
  declare module.exports: $Exports<'acorn/dist/acorn.es'>;
}
declare module 'acorn/dist/acorn.js' {
  declare module.exports: $Exports<'acorn/dist/acorn'>;
}
declare module 'acorn/dist/walk.es.js' {
  declare module.exports: $Exports<'acorn/dist/walk.es'>;
}
declare module 'acorn/dist/walk.js' {
  declare module.exports: $Exports<'acorn/dist/walk'>;
}
