// flow-typed signature: 1f0f6d337ff27816698c434bc74a499d
// flow-typed version: <<STUB>>/babel-7-jest_v~21.3.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-7-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-7-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-7-jest/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-7-jest/build/index.js' {
  declare module.exports: $Exports<'babel-7-jest/build/index'>;
}
