// flow-typed signature: 37f0ff074d1191de087d2b642efd7ba4
// flow-typed version: <<STUB>>/escodegen_v~1.9.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escodegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escodegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'escodegen/bin/escodegen' {
  declare module.exports: any;
}

declare module 'escodegen/bin/esgenerate' {
  declare module.exports: any;
}

declare module 'escodegen/escodegen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'escodegen/bin/escodegen.js' {
  declare module.exports: $Exports<'escodegen/bin/escodegen'>;
}
declare module 'escodegen/bin/esgenerate.js' {
  declare module.exports: $Exports<'escodegen/bin/esgenerate'>;
}
declare module 'escodegen/escodegen.js' {
  declare module.exports: $Exports<'escodegen/escodegen'>;
}
