// flow-typed signature: 82854667e8ed00f9a7c277142195d175
// flow-typed version: <<STUB>>/proxy-polyfill_v~0.1.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxy-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxy-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proxy-polyfill/proxy' {
  declare module.exports: any;
}

declare module 'proxy-polyfill/proxy.min' {
  declare module.exports: any;
}

declare module 'proxy-polyfill/suite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proxy-polyfill/proxy.js' {
  declare module.exports: $Exports<'proxy-polyfill/proxy'>;
}
declare module 'proxy-polyfill/proxy.min.js' {
  declare module.exports: $Exports<'proxy-polyfill/proxy.min'>;
}
declare module 'proxy-polyfill/suite.js' {
  declare module.exports: $Exports<'proxy-polyfill/suite'>;
}
