// flow-typed signature: 1c194173f513eabf7ed09d0f788a814e
// flow-typed version: <<STUB>>/typeface-bitter_v~0.0.44/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-bitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-bitter' {
  declare module.exports: any;
}
