// flow-typed signature: 706e870ee0f845b9635ddb4f615c5283
// flow-typed version: <<STUB>>/typeface-montserrat_v~0.0.45/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-montserrat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-montserrat' {
  declare module.exports: any;
}
