// flow-typed signature: 8af4d6921aa9313550a79a2d17f42ccc
// flow-typed version: <<STUB>>/webpack-config-assign_v~1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-config-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-config-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-config-assign/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/assign' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/util/assign-loaders' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/util/assign-module' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/util/assign-plugins' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/util/assign-property' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/lib/util/get-environment' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/assign' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/index' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/util/assign-loaders' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/util/assign-module' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/util/assign-plugins' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/util/assign-property' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/src/util/get-environment' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/assign.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/fixtures/base' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/fixtures/expected' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/fixtures/extend-two' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/fixtures/extend' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/index.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/util/assign-loaders.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/util/assign-module.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/util/assign-plugins.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/util/assign-property.test' {
  declare module.exports: any;
}

declare module 'webpack-config-assign/test/util/get-environment.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-config-assign/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'webpack-config-assign/coverage/lcov-report/prettify'>;
}
declare module 'webpack-config-assign/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'webpack-config-assign/coverage/lcov-report/sorter'>;
}
declare module 'webpack-config-assign/lib/assign.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/assign'>;
}
declare module 'webpack-config-assign/lib/index.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/index'>;
}
declare module 'webpack-config-assign/lib/util/assign-loaders.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/util/assign-loaders'>;
}
declare module 'webpack-config-assign/lib/util/assign-module.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/util/assign-module'>;
}
declare module 'webpack-config-assign/lib/util/assign-plugins.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/util/assign-plugins'>;
}
declare module 'webpack-config-assign/lib/util/assign-property.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/util/assign-property'>;
}
declare module 'webpack-config-assign/lib/util/get-environment.js' {
  declare module.exports: $Exports<'webpack-config-assign/lib/util/get-environment'>;
}
declare module 'webpack-config-assign/src/assign.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/assign'>;
}
declare module 'webpack-config-assign/src/index.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/index'>;
}
declare module 'webpack-config-assign/src/util/assign-loaders.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/util/assign-loaders'>;
}
declare module 'webpack-config-assign/src/util/assign-module.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/util/assign-module'>;
}
declare module 'webpack-config-assign/src/util/assign-plugins.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/util/assign-plugins'>;
}
declare module 'webpack-config-assign/src/util/assign-property.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/util/assign-property'>;
}
declare module 'webpack-config-assign/src/util/get-environment.js' {
  declare module.exports: $Exports<'webpack-config-assign/src/util/get-environment'>;
}
declare module 'webpack-config-assign/test/assign.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/assign.test'>;
}
declare module 'webpack-config-assign/test/fixtures/base.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/fixtures/base'>;
}
declare module 'webpack-config-assign/test/fixtures/expected.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/fixtures/expected'>;
}
declare module 'webpack-config-assign/test/fixtures/extend-two.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/fixtures/extend-two'>;
}
declare module 'webpack-config-assign/test/fixtures/extend.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/fixtures/extend'>;
}
declare module 'webpack-config-assign/test/index.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/index.test'>;
}
declare module 'webpack-config-assign/test/util/assign-loaders.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/util/assign-loaders.test'>;
}
declare module 'webpack-config-assign/test/util/assign-module.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/util/assign-module.test'>;
}
declare module 'webpack-config-assign/test/util/assign-plugins.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/util/assign-plugins.test'>;
}
declare module 'webpack-config-assign/test/util/assign-property.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/util/assign-property.test'>;
}
declare module 'webpack-config-assign/test/util/get-environment.test.js' {
  declare module.exports: $Exports<'webpack-config-assign/test/util/get-environment.test'>;
}
